### ISSUE TITLE
cookfood Plugin Issues

### ISSUE THREAD

**Issue by Ameno-Sagiri** [Chessnut/NSPlugins#1]
Alright I've noticed a couple issues with the food from cookfood. Call them suggestions if these were never intended.

It adds Hunger and Thirst meters. The problem is, NOTHING happens if these meters deplete to 0. Shouldn't it make you move slower, or damage you over time?

Another issue is the food does not replenish these meters, they replenish Health instead, and run off the original NutScript food base, which doesn't let you eat until your health is below 100.

I was hoping this would be more of a hunger mod due to the presence of these meters. Is this somehow an overlook?

**Comment by Ameno-Sagiri** [comment]
Update, looks like the plugin was using NutScripts food base rather than the food base in the plugin. I just replaced my NutScript base with this one instead.

The other problem still is that nothing seems to happen when your thirst and hunger meters hit 0.

**Comment by rebel1324** [comment]
Claryfied the cookfood plugin.
take a look.
