### ISSUE TITLE
[Suggestion] CWU Door Locks

### ISSUE THREAD

**Issue by KaiNW** [Chessnut/NSPlugins#4]
I got an idea for a Plugin:

CWU-Door Locks, theyre locks like the Combine locks but for CWU.

Why i dont do it myself?
I can code like a Nut.

**Comment by rebel1324** [comment]
2easy4me

**Comment by KaiNW** [comment]
Okay why you then didn't do that even :3

**Comment by JakeyCakey** [comment]
http://chessnut.info/forums/index.php/topic,40.0.html

It's already done by him.
