### ISSUE TITLE
Legs can't find File.

### ISSUE THREAD

**Issue by AtomiCAST** [Chessnut/NSPlugins#9]
I got an error saying that the script couldn't get AddCSLuaFile( "cl_legs_3_5_1.lua" )

**Comment by rebel1324** [comment]
provide us the source of the plugin

2014-04-17 21:22 GMT+09:00 Devastation notifications@github.com:

**Comment by AtomiCAST** [comment]
https://github.com/Chessnut/NSPlugins/tree/master/Legs

**Comment by robinlahtinen** [comment]
Thanks for reporting that!
Fixing and uploading new one now.
